config/routes.rb
Rails.application.routes.draw do

	root to: 'books#top'

	get 'top' => 'books#top'

	get 'books' => 'books#index'

	post 'books' => 'books#create'

	get 'books/:id' => 'books#show', as:'book'

	get 'books/:id/edit' => 'books#edit', as: 'edit_book'

	patch 'books/:id' => 'books#update', as: 'update_book'

	delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def top
	end

	def index
		@books = Book.all
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			flash[:create] = "Book was successfully created."
			redirect_to book_path(@book.id) #詳細画面に飛ぶ
		else
			@books = Book.all
			@book = Book.new
			render 'index'
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:update] = "Book was successfully updated."
			redirect_to book_path(@book.id)
		else
			@book = Book.new
			render "edit"
		end
	end

	def destroy
		book = Book.find(params[:id])
		if book.destroy
      		flash[:destroy] = "Book was successfully destroyed"
  	 		redirect_to books_path
    	else
      		@book = Book.new
      		@books = Book.all
      		render "index"
    	end
	end




	private

	def book_params
		params.require(:book).permit(:title, :body)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div class="alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= "error" +" "+ message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
	<p>Title</p>
	<p class= "text-field"><%= f.text_field :title %></p>
	<p>Body</p>
	<p class= "text-area"><%= f.text_area :body %></p>

	<p class= "text-update"><%= f.submit 'Update Book' %>
<% end %>

<!-- Edit|Backのボタンを作る -->
<%= link_to "show", book_path(@book.id) %> |
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<P class = "message"><%= flash[:destroy] %></P>

<body>

<h1>Books</h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
		</tr>
	</thead>

	<tbody>
	<% @books.each do |book| %>
		<tr>
		<td><%= book.title %></td>
		<td><%= book.body %></td>

	<td><%= link_to "Show", "/books/#{book.id}" %></td>
	<td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
	<td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>

		</tr>
		</tbody>
	<% end %>
	</tbody>
</table>

</body>

<h2>New book</h2>

<% if @book.errors.any? %>
  <div class="alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= "error" +" "+ message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book, url: '/books') do |f| %>

<div class="field">
  <p class= "new-title">Titel</p>
  <%= f.text_field :title %>
</div>

<div class="field">
  <p class= "new-body">Body</p>
  <%= f.text_area :body %>
</div>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<P class = "message"><%= flash[:create] %></P>
<P class = "message"><%= flash[:update] %></P>


<p class = "book-details"><b>Title: </b><%= @book.title %></p>
<p class = "book-details"><b>Body: </b><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %> |
<%= link_to "Back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p class= "book-details"><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や</p>
<p class= "book-details">印象を共有し交換することができます</p>


<p class= "book-details"><%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>